repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
    - id: black
      additional_dependencies: ['click==8.0.4']
      args: [--line-length=80]
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
    - id: isort
      name: isort (python)
- repo: https://github.com/pycqa/pydocstyle
  rev: '6.1.1'
  hooks:
    - id: pydocstyle
      exclude: ^(planckton/tests/|planckton/compounds/|planckton/forcefields/|setup.py)
      args: [--convention=numpy]
