name: planckton
channels:
  - conda-forge
dependencies:
  - ele=0.2.0
  - foyer=0.9.1
  - gmso=0.6.0
  - gsd=2.4.2
  - hoomd=2.9.6
  - mbuild=0.11.0
  - numpy=1.20
  - openbabel=3.1.1
  - openmm>=7.5
  - pip=20.2
  - pytest
  - pytest-cov
  - python=3.7
  - rdkit
  - signac=1.7.0
  - signac-flow=0.14.0
  - unyt=2.8.0
  - pip:
    - git+https://github.com/rsdefever/antefoyer.git
    - git+https://github.com/cmelab/planckton@v0.5.0
